shared:
  image: node:6

jobs:
  main:
    requires: [ ~pr, ~commit ]
    annotations:
      beta.screwdriver.cd/timeout: 100
    steps:
      - install: npm install
      - test: npm test
  publish-test:
    requires: [ main ]
    annotations:
      beta.screwdriver.cd/timeout: 10000000000000000000000
    steps:
      - echo: echo "this is test"
  publish-test2:
    requires: [ publish-test ]
    steps:
      - echo: echo "this is test"
  publish-test3:
    requires: [ publish-test2 ]
    steps:
      - echo: echo "this is test"
  publish-test4:
    requires: [ publish-test3 ]
    steps:
      - echo: echo "this is test"
