shared:
  image: node:6

jobs:
  main:
    requires: [ ~pr, ~commit ]
    annotations:
      beta.screwdriver.cd/timeout: 100
    steps:
      - echo: echo "this is annotation test."
      - test: |
          echo "nToken: ";
          echo "SD_TOKEN: $SD_TOKEN";
  publish-test:
    requires: [ main ]
    annotations:
      beta.screwdriver.cd/timeout: 10000000000000000000000
    steps:
      - echo: echo "this is annotation test. over MAX_BUILD_TIMEOUT"
      - test: |
          echo "nToken: ";
          echo "SD_TOKEN: $SD_TOKEN";
  publish-test2:
    requires: [ publish-test ]
    steps:
      - echo: echo "this is no annotation. It should be default build timeout value (90min.)"
      - test: |
          echo "nToken: ";
          echo "SD_TOKEN: $SD_TOKEN";
