shared:
  image: node:6

jobs:
  main:
    requires: [ ~pr, ~commit ]
    annotations:
      beta.screwdriver.cd/timeout: 100
    steps:
      - install: npm install
      - test: npm test
  publish-test:
    requires: [ main ]
    steps:
      - echo: echo "this is test"
  publish:
    requires: [ publish-test ]
    steps:
      - set_access: npm config set access public > /dev/null 2>&1
      - set_token: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN > /dev/null 2>&1
      - publish_npm: npm publish
    secrets:
      - NPM_TOKEN
